<?php

namespace ContainerGtDNFxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BGl6S9EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bGl6S9E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bGl6S9E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authorization' => ['privates', 'App\\Service\\Authorization', 'getAuthorizationService', true],
            'jwt' => ['privates', 'App\\Service\\JWT', 'getJWTService', true],
        ], [
            'authorization' => 'App\\Service\\Authorization',
            'jwt' => 'App\\Service\\JWT',
        ]);
    }
}
