<?php

namespace ContainerGtDNFxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Authorization' shared autowired service.
     *
     * @return \App\Service\Authorization
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Authorization.php';
        include_once \dirname(__DIR__, 4).'/src/Service/JWT.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';

        return $container->privates['App\\Service\\Authorization'] = new \App\Service\Authorization(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Service\\JWT'] ??= new \App\Service\JWT()), ($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()));
    }
}
