<?php

namespace ContainerGtDNFxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthAPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AuthAPI' shared autowired service.
     *
     * @return \App\Controller\AuthAPI
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AuthAPI.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/JWT.php';

        $container->services['App\\Controller\\AuthAPI'] = $instance = new \App\Controller\AuthAPI(($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()), ($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->privates['App\\Service\\JWT'] ??= new \App\Service\JWT()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AuthAPI', $container));

        return $instance;
    }
}
