<?php

namespace ContainerGtDNFxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStandFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\StandForm' shared autowired service.
     *
     * @return \App\Form\StandForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/StandForm.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';

        return $container->privates['App\\Form\\StandForm'] = new \App\Form\StandForm(($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()));
    }
}
