<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z225LaHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z225LaH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z225LaH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authorization' => ['privates', 'App\\Service\\Authorization', 'getAuthorizationService', true],
        ], [
            'authorization' => 'App\\Service\\Authorization',
        ]);
    }
}
