<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCitiesManagmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CitiesManagment' shared autowired service.
     *
     * @return \App\Controller\CitiesManagment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CitiesManagment.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';

        $container->services['App\\Controller\\CitiesManagment'] = $instance = new \App\Controller\CitiesManagment(($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CitiesManagment', $container));

        return $instance;
    }
}
