<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\JWT' shared autowired service.
     *
     * @return \App\Service\JWT
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/JWT.php';

        return $container->privates['App\\Service\\JWT'] = new \App\Service\JWT();
    }
}
