<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LoginForm' shared autowired service.
     *
     * @return \App\Form\LoginForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LoginForm.php';

        return $container->privates['App\\Form\\LoginForm'] = new \App\Form\LoginForm();
    }
}
