<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStandAPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StandAPI' shared autowired service.
     *
     * @return \App\Controller\StandAPI
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Trait/EntityViolations.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StandAPI.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';

        $container->services['App\\Controller\\StandAPI'] = $instance = new \App\Controller\StandAPI(($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()), ($container->privates['validator'] ?? $container->load('getValidatorService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\StandAPI', $container));

        return $instance;
    }
}
