<?php

namespace ContainerRBpqxUv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserAPI' shared autowired service.
     *
     * @return \App\Controller\UserAPI
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Trait/EntityViolations.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserAPI.php';
        include_once \dirname(__DIR__, 4).'/lib/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MysqlStorage.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->services['App\\Controller\\UserAPI'] = $instance = new \App\Controller\UserAPI(($container->privates['App\\Service\\MysqlStorage'] ??= new \App\Service\MysqlStorage()), ($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\UserAPI', $container));

        return $instance;
    }
}
