<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGtDNFxz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGtDNFxz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGtDNFxz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGtDNFxz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGtDNFxz\App_KernelDevDebugContainer([
    'container.build_hash' => 'GtDNFxz',
    'container.build_id' => '3c068b68',
    'container.build_time' => 1710215120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGtDNFxz');
